# ç©ºè¡Œè¿½åŠ 
add_newline = true
command_timeout = 5000

# ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆæ™‚é–“
scan_timeout = 10

[directory]
truncation_length = 2
truncate_to_repo = false

# è¨˜å·ã®è¨­å®š
[character]
# ã‚³ãƒãƒ³ãƒ‰æˆåŠŸæ™‚
success_symbol = "[â–¶](bold green)"
# ã‚³ãƒãƒ³ãƒ‰å¤±æ•—æ™‚
error_symbol = "[â–¶](bold red)"

[git_branch]
symbol = "ğŸŒ± "

[nodejs]
format = "nodejs [$version](bold green) "

[php]
disabled = true

[package]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true
